
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 30 15:52:33 CET 2012
//----------------------------------------------------

package lea;

import java_cup.runtime.*;
import java.io.*;
import java.lang.*;
import java.util.*;
import lea.types.*;
import lea.constants.*;
import lea.syntax.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Fri Nov 30 15:52:33 CET 2012
  */
public class LeaParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public LeaParser() {super();}

  /** Constructor which sets the default scanner. */
  public LeaParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public LeaParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\024\000\002\002\004\000\002\002\003\000\002\002" +
    "\004\000\002\002\004\000\002\002\003\000\002\007\003" +
    "\000\002\007\003\000\002\007\003\000\002\007\003\000" +
    "\002\007\003\000\002\003\006\000\002\004\012\000\002" +
    "\013\002\000\002\012\006\000\002\005\004\000\002\005" +
    "\003\000\002\006\006\000\002\010\005\000\002\010\003" +
    "\000\002\011\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\050\000\006\006\010\022\007\001\002\000\010\002" +
    "\000\006\010\022\007\001\002\000\010\002\ufffd\006\010" +
    "\022\007\001\002\000\004\002\050\001\002\000\004\004" +
    "\045\001\002\000\004\022\011\001\002\000\004\007\012" +
    "\001\002\000\004\022\015\001\002\000\006\010\uffef\021" +
    "\uffef\001\002\000\006\010\026\021\025\001\002\000\004" +
    "\011\016\001\002\000\014\014\024\015\022\016\017\017" +
    "\023\020\021\001\002\000\012\005\ufff9\010\ufff9\012\ufff9" +
    "\021\ufff9\001\002\000\006\010\uffee\021\uffee\001\002\000" +
    "\012\005\ufff8\010\ufff8\012\ufff8\021\ufff8\001\002\000\012" +
    "\005\ufffb\010\ufffb\012\ufffb\021\ufffb\001\002\000\012\005" +
    "\ufffa\010\ufffa\012\ufffa\021\ufffa\001\002\000\012\005\ufffc" +
    "\010\ufffc\012\ufffc\021\ufffc\001\002\000\004\022\015\001" +
    "\002\000\004\011\027\001\002\000\014\014\024\015\022" +
    "\016\017\017\023\020\021\001\002\000\004\012\031\001" +
    "\002\000\004\022\ufff5\001\002\000\010\002\ufff6\006\ufff6" +
    "\022\ufff6\001\002\000\004\022\036\001\002\000\006\013" +
    "\ufff2\022\ufff2\001\002\000\006\013\043\022\036\001\002" +
    "\000\004\011\037\001\002\000\014\014\024\015\022\016" +
    "\017\017\023\020\021\001\002\000\004\005\041\001\002" +
    "\000\006\013\ufff1\022\ufff1\001\002\000\006\013\ufff3\022" +
    "\ufff3\001\002\000\010\002\ufff4\006\ufff4\022\ufff4\001\002" +
    "\000\006\010\ufff0\021\ufff0\001\002\000\004\023\046\001" +
    "\002\000\004\005\047\001\002\000\010\002\ufff7\006\ufff7" +
    "\022\ufff7\001\002\000\004\002\001\001\002\000\004\002" +
    "\uffff\001\002\000\004\002\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\050\000\010\002\005\003\004\004\003\001\001\000" +
    "\010\002\051\003\004\004\003\001\001\000\010\002\050" +
    "\003\004\004\003\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\010\013" +
    "\011\012\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\007\017\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\011\043\001\001" +
    "\000\002\001\001\000\004\007\027\001\001\000\004\012" +
    "\031\001\001\000\004\013\032\001\001\000\002\001\001" +
    "\000\006\005\034\006\033\001\001\000\002\001\001\000" +
    "\004\006\041\001\001\000\002\001\001\000\004\007\037" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$LeaParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$LeaParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$LeaParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


 
 public void report_fatal_error(String message, Object info) 
  {
  	report_error( message,  info);
  }
  
  public void report_error(String message, Object info) 
  {
  	java_cup.runtime.Symbol symb = (java_cup.runtime.Symbol)info;
  	System.out.println("Ligne : " + symb.left + " Colonne : " + symb.right + "   : " + message);
  }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$LeaParser$actions {
  private final LeaParser parser;

  /** Constructor */
  CUP$LeaParser$actions(LeaParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$LeaParser$do_action(
    int                        CUP$LeaParser$act_num,
    java_cup.runtime.lr_parser CUP$LeaParser$parser,
    java.util.Stack            CUP$LeaParser$stack,
    int                        CUP$LeaParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$LeaParser$result;

      /* select the action based on the action number */
      switch (CUP$LeaParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // functDecl ::= IDENTIFIER COLON type 
            {
              ArgumentInfo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = new ArgumentInfo(id, t); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("functDecl",7, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // functDecls ::= functDecl 
            {
              LinkedList<ArgumentInfo> RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		ArgumentInfo f = (ArgumentInfo)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 
		LinkedList<ArgumentInfo> l = new LinkedList<ArgumentInfo>();
		l.add(f);
		RESULT = l;  
	
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("functDecls",6, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // functDecls ::= functDecls COMMA functDecl 
            {
              LinkedList<ArgumentInfo> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).right;
		LinkedList<ArgumentInfo> l = (LinkedList<ArgumentInfo>)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		ArgumentInfo f = (ArgumentInfo)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		
		l.add(f);
		RESULT = l;
	
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("functDecls",6, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // decl ::= IDENTIFIER COLON type SEMIC 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).value;
		
	if(Main.currentNode != null)
	{
		Main.currentNode.getEnvironment().put(id, t);
		System.out.println("ENV : " + Main.currentNode.getEnvironment().toString());
	}
	else
		System.out.println("DÉCLARATION VARIABLE GLOBALE INTERDITE!! FAUT GÉRER CA ICI!");

              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("decl",4, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // decls ::= decl 
            {
              Object RESULT =null;

              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("decls",3, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // decls ::= decls decl 
            {
              Object RESULT =null;

              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("decls",3, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // block ::= LBRACE NT$0 decls RBRACE 
            {
              SyntaxTree RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (SyntaxTree) ((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).value;

              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("block",8, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // NT$0 ::= 
            {
              SyntaxTree RESULT =null;

	    System.out.println("BLOCK ");
	    SyntaxTree sTree = new SyntaxTree(null, null);
	    
	    Main.currentNode = sTree;
	    RESULT = sTree;
	
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("NT$0",9, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // funct ::= FUNCTION IDENTIFIER LPAR functDecls RPAR COLON type block 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-6)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-6)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-6)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-4)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-4)).right;
		LinkedList<ArgumentInfo> f = (LinkedList<ArgumentInfo>)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-4)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		SyntaxTree b = (SyntaxTree)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		
			FunctionInfo fctInfo = new FunctionInfo(f, t, b);
			Main.fctTable.put(id, fctInfo);
			
			System.out.println("\n\nFCT : " + Main.fctTable.toString() + "\n");
		
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("funct",2, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-7)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // constDecl ::= IDENTIFIER EQ INTEGER SEMIC 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).value;
		
		  	Main.constTable.put(id, new IntConstant(i));
		  	System.out.println("\nCONST : " + Main.constTable.toString() + "\n");
		
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("constDecl",1, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // type ::= BOOL 
            {
              Type RESULT =null;
		 RESULT = new BoolType(); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // type ::= STRING 
            {
              Type RESULT =null;
		 RESULT = new StringType(); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // type ::= CHAR 
            {
              Type RESULT =null;
		 RESULT = new CharType(); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // type ::= FLOAT 
            {
              Type RESULT =null;
		 RESULT = new FloatType();  
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // type ::= INT 
            {
              Type RESULT =null;
		 RESULT = new IntType();  
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // axiom ::= constDecl 
            {
              Object RESULT =null;

              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("axiom",0, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // axiom ::= funct axiom 
            {
              Object RESULT =null;

              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("axiom",0, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // axiom ::= constDecl axiom 
            {
              Object RESULT =null;

              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("axiom",0, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // axiom ::= funct 
            {
              Object RESULT =null;

              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("axiom",0, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= axiom EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).value;
		RESULT = start_val;
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$LeaParser$parser.done_parsing();
          return CUP$LeaParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

