
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Dec 01 16:14:23 CET 2012
//----------------------------------------------------

package lea;

import java_cup.runtime.*;
import java.io.*;
import java.lang.*;
import java.util.*;
import lea.types.*;
import lea.constants.*;
import lea.syntax.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sat Dec 01 16:14:23 CET 2012
  */
public class LeaParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public LeaParser() {super();}

  /** Constructor which sets the default scanner. */
  public LeaParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public LeaParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\064\000\002\002\004\000\002\002\003\000\002\002" +
    "\004\000\002\002\004\000\002\002\003\000\002\007\003" +
    "\000\002\007\003\000\002\007\003\000\002\007\003\000" +
    "\002\007\003\000\002\003\006\000\002\020\002\000\002" +
    "\012\006\000\002\006\006\000\002\006\010\000\002\016" +
    "\003\000\002\016\003\000\002\004\012\000\002\010\005" +
    "\000\002\010\003\000\002\011\005\000\002\014\011\000" +
    "\002\014\007\000\002\014\007\000\002\014\006\000\002" +
    "\014\003\000\002\013\004\000\002\013\003\000\002\015" +
    "\005\000\002\015\005\000\002\015\005\000\002\015\005" +
    "\000\002\015\005\000\002\015\005\000\002\015\005\000" +
    "\002\015\005\000\002\015\005\000\002\015\005\000\002" +
    "\015\004\000\002\015\005\000\002\015\005\000\002\015" +
    "\005\000\002\015\004\000\002\015\003\000\002\015\003" +
    "\000\002\015\003\000\002\015\003\000\002\015\003\000" +
    "\002\015\005\000\002\017\003\000\002\021\002\000\002" +
    "\017\006" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\150\000\006\005\010\050\007\001\002\000\010\002" +
    "\000\005\010\050\007\001\002\000\010\002\ufffd\005\010" +
    "\050\007\001\002\000\004\002\150\001\002\000\004\040" +
    "\145\001\002\000\004\050\011\001\002\000\004\006\012" +
    "\001\002\000\004\050\015\001\002\000\006\007\uffee\020" +
    "\uffee\001\002\000\006\007\026\020\025\001\002\000\004" +
    "\010\016\001\002\000\014\013\024\014\022\015\017\016" +
    "\023\017\021\001\002\000\014\004\ufff9\007\ufff9\011\ufff9" +
    "\020\ufff9\026\ufff9\001\002\000\006\007\uffed\020\uffed\001" +
    "\002\000\014\004\ufff8\007\ufff8\011\ufff8\020\ufff8\026\ufff8" +
    "\001\002\000\014\004\ufffb\007\ufffb\011\ufffb\020\ufffb\026" +
    "\ufffb\001\002\000\014\004\ufffa\007\ufffa\011\ufffa\020\ufffa" +
    "\026\ufffa\001\002\000\014\004\ufffc\007\ufffc\011\ufffc\020" +
    "\ufffc\026\ufffc\001\002\000\004\050\015\001\002\000\004" +
    "\010\027\001\002\000\014\013\024\014\022\015\017\016" +
    "\023\017\021\001\002\000\004\011\031\001\002\000\010" +
    "\021\ufff6\024\ufff6\050\ufff6\001\002\000\010\002\ufff0\005" +
    "\ufff0\050\ufff0\001\002\000\010\021\042\024\041\050\040" +
    "\001\002\000\012\012\uffe6\021\uffe6\024\uffe6\050\uffe6\001" +
    "\002\000\012\012\uffe8\021\uffe8\024\uffe8\050\uffe8\001\002" +
    "\000\012\012\143\021\042\024\041\050\040\001\002\000" +
    "\004\026\137\001\002\000\010\010\131\026\uffd0\027\117" +
    "\001\002\000\004\006\125\001\002\000\004\006\043\001" +
    "\002\000\024\006\053\031\057\043\044\050\055\051\046" +
    "\052\050\053\051\055\045\056\054\001\002\000\024\006" +
    "\053\031\057\043\044\050\055\051\046\052\050\053\051" +
    "\055\045\056\054\001\002\000\040\004\ufff2\007\ufff2\020" +
    "\ufff2\032\ufff2\033\ufff2\034\ufff2\035\ufff2\036\ufff2\037\ufff2" +
    "\040\ufff2\041\ufff2\042\ufff2\043\ufff2\045\ufff2\046\ufff2\001" +
    "\002\000\040\004\uffd6\007\uffd6\020\uffd6\032\uffd6\033\uffd6" +
    "\034\uffd6\035\uffd6\036\uffd6\037\uffd6\040\uffd6\041\uffd6\042" +
    "\uffd6\043\uffd6\045\uffd6\046\uffd6\001\002\000\040\004\uffd2" +
    "\007\uffd2\020\uffd2\032\uffd2\033\uffd2\034\uffd2\035\uffd2\036" +
    "\uffd2\037\uffd2\040\uffd2\041\uffd2\042\uffd2\043\uffd2\045\uffd2" +
    "\046\uffd2\001\002\000\040\004\uffd5\007\uffd5\020\uffd5\032" +
    "\uffd5\033\uffd5\034\uffd5\035\uffd5\036\uffd5\037\uffd5\040\uffd5" +
    "\041\uffd5\042\uffd5\043\uffd5\045\uffd5\046\uffd5\001\002\000" +
    "\040\004\uffd4\007\uffd4\020\uffd4\032\uffd4\033\uffd4\034\uffd4" +
    "\035\uffd4\036\uffd4\037\uffd4\040\uffd4\041\uffd4\042\uffd4\043" +
    "\uffd4\045\uffd4\046\uffd4\001\002\000\040\004\uffd3\007\uffd3" +
    "\020\uffd3\032\uffd3\033\uffd3\034\uffd3\035\uffd3\036\uffd3\037" +
    "\uffd3\040\uffd3\041\uffd3\042\uffd3\043\uffd3\045\uffd3\046\uffd3" +
    "\001\002\000\024\006\053\031\057\043\044\050\055\051" +
    "\046\052\050\053\051\055\045\056\054\001\002\000\040" +
    "\004\ufff1\007\ufff1\020\ufff1\032\ufff1\033\ufff1\034\ufff1\035" +
    "\ufff1\036\ufff1\037\ufff1\040\ufff1\041\ufff1\042\ufff1\043\ufff1" +
    "\045\ufff1\046\ufff1\001\002\000\044\004\uffd0\007\uffd0\020" +
    "\uffd0\026\uffd0\027\117\032\uffd0\033\uffd0\034\uffd0\035\uffd0" +
    "\036\uffd0\037\uffd0\040\uffd0\041\uffd0\042\uffd0\043\uffd0\045" +
    "\uffd0\046\uffd0\001\002\000\036\007\113\020\072\032\062" +
    "\033\075\034\074\035\071\036\067\037\063\040\066\041" +
    "\073\042\065\043\061\045\064\046\070\001\002\000\024" +
    "\006\053\031\057\043\044\050\055\051\046\052\050\053" +
    "\051\055\045\056\054\001\002\000\040\004\uffd7\007\uffd7" +
    "\020\072\032\062\033\075\034\074\035\071\036\067\037" +
    "\063\040\066\041\073\042\065\043\061\045\064\046\070" +
    "\001\002\000\024\006\053\031\057\043\044\050\055\051" +
    "\046\052\050\053\051\055\045\056\054\001\002\000\024" +
    "\006\053\031\057\043\044\050\055\051\046\052\050\053" +
    "\051\055\045\056\054\001\002\000\024\006\053\031\057" +
    "\043\044\050\055\051\046\052\050\053\051\055\045\056" +
    "\054\001\002\000\024\006\053\031\057\043\044\050\055" +
    "\051\046\052\050\053\051\055\045\056\054\001\002\000" +
    "\024\006\053\031\057\043\044\050\055\051\046\052\050" +
    "\053\051\055\045\056\054\001\002\000\024\006\053\031" +
    "\057\043\044\050\055\051\046\052\050\053\051\055\045" +
    "\056\054\001\002\000\024\006\053\031\057\043\044\050" +
    "\055\051\046\052\050\053\051\055\045\056\054\001\002" +
    "\000\024\006\053\031\057\043\044\050\055\051\046\052" +
    "\050\053\051\055\045\056\054\001\002\000\024\006\053" +
    "\031\057\043\044\050\055\051\046\052\050\053\051\055" +
    "\045\056\054\001\002\000\024\006\053\031\057\043\044" +
    "\050\055\051\046\052\050\053\051\055\045\056\054\001" +
    "\002\000\024\006\053\031\057\043\044\050\055\051\046" +
    "\052\050\053\051\055\045\056\054\001\002\000\024\006" +
    "\053\031\057\043\044\050\055\051\046\052\050\053\051" +
    "\055\045\056\054\001\002\000\024\006\053\031\057\043" +
    "\044\050\055\051\046\052\050\053\051\055\045\056\054" +
    "\001\002\000\040\004\uffe4\007\uffe4\020\uffe4\032\uffe4\033" +
    "\uffe4\034\074\035\071\036\067\037\063\040\066\041\073" +
    "\042\065\043\061\045\064\046\070\001\002\000\040\004" +
    "\uffe3\007\uffe3\020\uffe3\032\uffe3\033\uffe3\034\uffe3\035\uffe3" +
    "\036\uffe3\037\uffe3\040\uffe3\041\uffe3\042\065\043\061\045" +
    "\064\046\070\001\002\000\040\004\uffde\007\uffde\020\uffde" +
    "\032\uffde\033\uffde\034\uffde\035\uffde\036\uffde\037\uffde\040" +
    "\uffde\041\uffde\042\065\043\061\045\064\046\070\001\002" +
    "\000\040\004\uffd1\007\uffd1\020\uffd1\032\062\033\075\034" +
    "\074\035\071\036\067\037\063\040\066\041\073\042\065" +
    "\043\061\045\064\046\070\001\002\000\040\004\uffe2\007" +
    "\uffe2\020\uffe2\032\uffe2\033\uffe2\034\uffe2\035\uffe2\036\uffe2" +
    "\037\uffe2\040\uffe2\041\uffe2\042\065\043\061\045\064\046" +
    "\070\001\002\000\040\004\uffd9\007\uffd9\020\uffd9\032\uffd9" +
    "\033\uffd9\034\uffd9\035\uffd9\036\uffd9\037\uffd9\040\uffd9\041" +
    "\uffd9\042\uffd9\043\uffd9\045\uffd9\046\uffd9\001\002\000\040" +
    "\004\uffe1\007\uffe1\020\uffe1\032\uffe1\033\uffe1\034\uffe1\035" +
    "\uffe1\036\uffe1\037\uffe1\040\uffe1\041\uffe1\042\065\043\061" +
    "\045\064\046\070\001\002\000\040\004\uffdf\007\uffdf\020" +
    "\uffdf\032\uffdf\033\uffdf\034\uffdf\035\uffdf\036\uffdf\037\uffdf" +
    "\040\uffdf\041\uffdf\042\065\043\061\045\064\046\070\001" +
    "\002\000\040\004\uffdd\007\uffdd\020\uffdd\032\uffdd\033\uffdd" +
    "\034\uffdd\035\uffdd\036\uffdd\037\uffdd\040\uffdd\041\uffdd\042" +
    "\uffdd\043\uffdd\045\064\046\070\001\002\000\040\004\uffda" +
    "\007\uffda\020\uffda\032\uffda\033\uffda\034\uffda\035\uffda\036" +
    "\uffda\037\uffda\040\uffda\041\uffda\042\uffda\043\uffda\045\uffda" +
    "\046\uffda\001\002\000\040\004\uffe0\007\uffe0\020\uffe0\032" +
    "\uffe0\033\uffe0\034\uffe0\035\uffe0\036\uffe0\037\uffe0\040\uffe0" +
    "\041\uffe0\042\065\043\061\045\064\046\070\001\002\000" +
    "\040\004\uffe5\007\uffe5\020\uffe5\032\uffe5\033\075\034\074" +
    "\035\071\036\067\037\063\040\066\041\073\042\065\043" +
    "\061\045\064\046\070\001\002\000\040\004\uffdc\007\uffdc" +
    "\020\uffdc\032\uffdc\033\uffdc\034\uffdc\035\uffdc\036\uffdc\037" +
    "\uffdc\040\uffdc\041\uffdc\042\uffdc\043\uffdc\045\064\046\070" +
    "\001\002\000\004\011\031\001\002\000\014\012\uffea\021" +
    "\uffea\022\115\024\uffea\050\uffea\001\002\000\004\011\031" +
    "\001\002\000\012\012\uffec\021\uffec\024\uffec\050\uffec\001" +
    "\002\000\004\050\uffcf\001\002\000\004\050\055\001\002" +
    "\000\042\004\uffce\007\uffce\020\uffce\026\uffce\032\uffce\033" +
    "\uffce\034\uffce\035\uffce\036\uffce\037\uffce\040\uffce\041\uffce" +
    "\042\uffce\043\uffce\045\uffce\046\uffce\001\002\000\036\007" +
    "\123\020\072\032\062\033\075\034\074\035\071\036\067" +
    "\037\063\040\066\041\073\042\065\043\061\045\064\046" +
    "\070\001\002\000\040\004\uffd8\007\uffd8\020\uffd8\032\uffd8" +
    "\033\uffd8\034\uffd8\035\uffd8\036\uffd8\037\uffd8\040\uffd8\041" +
    "\uffd8\042\uffd8\043\uffd8\045\uffd8\046\uffd8\001\002\000\040" +
    "\004\uffdb\007\uffdb\020\uffdb\032\uffdb\033\uffdb\034\uffdb\035" +
    "\uffdb\036\uffdb\037\uffdb\040\uffdb\041\uffdb\042\uffdb\043\uffdb" +
    "\045\uffdb\046\uffdb\001\002\000\024\006\053\031\057\043" +
    "\044\050\055\051\046\052\050\053\051\055\045\056\054" +
    "\001\002\000\036\007\127\020\072\032\062\033\075\034" +
    "\074\035\071\036\067\037\063\040\066\041\073\042\065" +
    "\043\061\045\064\046\070\001\002\000\004\011\031\001" +
    "\002\000\012\012\uffeb\021\uffeb\024\uffeb\050\uffeb\001\002" +
    "\000\014\013\024\014\022\015\017\016\023\017\021\001" +
    "\002\000\006\004\133\026\134\001\002\000\012\012\ufff4" +
    "\021\ufff4\024\ufff4\050\ufff4\001\002\000\024\006\053\031" +
    "\057\043\044\050\055\051\046\052\050\053\051\055\045" +
    "\056\054\001\002\000\036\004\136\020\072\032\062\033" +
    "\075\034\074\035\071\036\067\037\063\040\066\041\073" +
    "\042\065\043\061\045\064\046\070\001\002\000\012\012" +
    "\ufff3\021\ufff3\024\ufff3\050\ufff3\001\002\000\024\006\053" +
    "\031\057\043\044\050\055\051\046\052\050\053\051\055" +
    "\045\056\054\001\002\000\036\004\141\020\072\032\062" +
    "\033\075\034\074\035\071\036\067\037\063\040\066\041" +
    "\073\042\065\043\061\045\064\046\070\001\002\000\012" +
    "\012\uffe9\021\uffe9\024\uffe9\050\uffe9\001\002\000\012\012" +
    "\uffe7\021\uffe7\024\uffe7\050\uffe7\001\002\000\020\002\ufff5" +
    "\005\ufff5\012\ufff5\021\ufff5\022\ufff5\024\ufff5\050\ufff5\001" +
    "\002\000\006\007\uffef\020\uffef\001\002\000\004\051\146" +
    "\001\002\000\004\004\147\001\002\000\010\002\ufff7\005" +
    "\ufff7\050\ufff7\001\002\000\004\002\001\001\002\000\004" +
    "\002\uffff\001\002\000\004\002\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\150\000\010\002\005\003\004\004\003\001\001\000" +
    "\010\002\151\003\004\004\003\001\001\000\010\002\150" +
    "\003\004\004\003\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\010\013" +
    "\011\012\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\007\017\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\011\143\001\001" +
    "\000\002\001\001\000\004\007\027\001\001\000\004\012" +
    "\031\001\001\000\004\020\032\001\001\000\002\001\001" +
    "\000\012\006\034\013\035\014\033\017\036\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\006\034\014\141" +
    "\017\036\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\015\055\016\046" +
    "\017\051\001\001\000\010\015\123\016\046\017\051\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\015\121\016\046\017\051\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\015\057\016" +
    "\046\017\051\001\001\000\002\001\001\000\010\015\111" +
    "\016\046\017\051\001\001\000\010\015\110\016\046\017" +
    "\051\001\001\000\010\015\107\016\046\017\051\001\001" +
    "\000\010\015\106\016\046\017\051\001\001\000\010\015" +
    "\105\016\046\017\051\001\001\000\010\015\104\016\046" +
    "\017\051\001\001\000\010\015\103\016\046\017\051\001" +
    "\001\000\010\015\102\016\046\017\051\001\001\000\010" +
    "\015\101\016\046\017\051\001\001\000\010\015\100\016" +
    "\046\017\051\001\001\000\010\015\077\016\046\017\051" +
    "\001\001\000\010\015\076\016\046\017\051\001\001\000" +
    "\010\015\075\016\046\017\051\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\012\113" +
    "\001\001\000\002\001\001\000\004\012\115\001\001\000" +
    "\002\001\001\000\004\021\117\001\001\000\004\017\120" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\015\125\016\046\017\051" +
    "\001\001\000\002\001\001\000\004\012\127\001\001\000" +
    "\002\001\001\000\004\007\131\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\015\134\016\046\017\051\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\015\137" +
    "\016\046\017\051\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$LeaParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$LeaParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$LeaParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


 
 public void report_fatal_error(String message, Object info) 
  {
  	report_error( message,  info);
  }
  
  public void report_error(String message, Object info) 
  {
  	java_cup.runtime.Symbol symb = (java_cup.runtime.Symbol)info;
  	System.out.println("Ligne : " + symb.left + " Colonne : " + symb.right + "   : " + message);
  }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$LeaParser$actions {
  private final LeaParser parser;

  /** Constructor */
  CUP$LeaParser$actions(LeaParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$LeaParser$do_action(
    int                        CUP$LeaParser$act_num,
    java_cup.runtime.lr_parser CUP$LeaParser$parser,
    java.util.Stack            CUP$LeaParser$stack,
    int                        CUP$LeaParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$LeaParser$result;

      /* select the action based on the action number */
      switch (CUP$LeaParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // variable ::= IDENTIFIER SLOT NT$1 variable 
            {
              VariableLeaf RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (VariableLeaf) ((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)).value;
		int v1left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int v1right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		VariableLeaf v1 = (VariableLeaf)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("variable",13, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // NT$1 ::= 
            {
              VariableLeaf RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).value;

    		
    	
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("NT$1",15, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // variable ::= IDENTIFIER 
            {
              VariableLeaf RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		    		
    		//TODO MHB : RAISE ERROR IF t == null
    		
    		Type t = Main.currentNode.getEnvironment().get(id).getType();
    		RESULT = new VariableLeaf(id, t);
    	
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("variable",13, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expr ::= expr COMMA expr 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = new ListNode(new Succ(e1, e2)); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expr ::= BOOLEXP 
            {
              Expression RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 
		RESULT = new ConstantLeaf(new BoolConstant(b), new BoolType()); 
		
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expr ::= variable 
            {
              Expression RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		VariableLeaf v = (VariableLeaf)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = v; 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expr ::= STRINGEXP 
            {
              Expression RESULT =null;
		int stleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int stright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		String st = (String)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 
		RESULT = new ConstantLeaf(new StringConstant(st), new StringType());  
		
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expr ::= FLOATEXP 
            {
              Expression RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		String d = (String)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 
		RESULT = new ConstantLeaf(new FloatConstant(d), new FloatType()); 
		
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expr ::= INTEGER 
            {
              Expression RESULT =null;
		int itleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int itright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		String it = (String)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 
		RESULT = new ConstantLeaf(new IntConstant(it), new IntType()); 
		
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expr ::= RETURN expr 
            {
              Expression RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = new ReturnNode(e); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expr ::= LPAR expr RPAR 
            {
              Expression RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).value;
		 RESULT = e; 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expr ::= expr DIV expr 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = new Expression(e1, e2); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expr ::= expr MULT expr 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = new Expression(e1, e2); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expr ::= MINUS expr 
            {
              Expression RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = new Expression(e, null); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expr ::= expr MINUS expr 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = new Expression(e1, e2); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expr ::= expr PLUS expr 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = new Expression(e1, e2); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expr ::= expr DIFF expr 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = new Expression(e1, e2); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expr ::= expr EQ expr 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = new Expression(e1, e2); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expr ::= expr GE expr 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = new Expression(e1, e2); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expr ::= expr LE expr 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = new Expression(e1, e2); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expr ::= expr GT expr 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = new Expression(e1, e2); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expr ::= expr LT expr 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = new Expression(e1, e2); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expr ::= expr OR expr 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = new Expression(e1, e2); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expr ::= expr AND expr 
            {
              Expression RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).right;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = new Expression(e1, e2); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("expr",11, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // instrs ::= instr 
            {
              Instruction RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		Instruction i = (Instruction)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = i; 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("instrs",9, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // instrs ::= instrs instr 
            {
              Instruction RESULT =null;
		int i1left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).left;
		int i1right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).right;
		Instruction i1 = (Instruction)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).value;
		int i2left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int i2right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		Instruction i2 = (Instruction)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = new Succ(i1, i2); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("instrs",9, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // instr ::= decl 
            {
              Instruction RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		Instruction d = (Instruction)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = d;	
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("instr",10, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // instr ::= variable AFF expr SEMIC 
            {
              Instruction RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)).right;
		VariableLeaf v = (VariableLeaf)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).value;
		 
		//TODO MHB : TYPE CHECKING HERE 
		RESULT = new Assignment(v, e); 
	
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("instr",10, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // instr ::= IF LPAR expr RPAR block 
            {
              Instruction RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		SyntaxTree i = (SyntaxTree)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = new Condition(e, i); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("instr",10, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-4)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // instr ::= WHILE LPAR expr RPAR block 
            {
              Instruction RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		SyntaxTree i = (SyntaxTree)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = new Loop(e, i); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("instr",10, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-4)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // instr ::= IF LPAR expr RPAR block ELSE block 
            {
              Instruction RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-4)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-4)).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-4)).value;
		int i1left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).left;
		int i1right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).right;
		SyntaxTree i1 = (SyntaxTree)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).value;
		int i2left = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int i2right = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		SyntaxTree i2 = (SyntaxTree)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = new Condition(e, new ElseCondition(i1, i2)); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("instr",10, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-6)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // functDecl ::= IDENTIFIER COLON type 
            {
              ArgumentInfo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 RESULT = new ArgumentInfo(id, t); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("functDecl",7, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // functDecls ::= functDecl 
            {
              LinkedList<ArgumentInfo> RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		ArgumentInfo f = (ArgumentInfo)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		 
		LinkedList<ArgumentInfo> l = new LinkedList<ArgumentInfo>();
		l.add(f);
		RESULT = l;  
	
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("functDecls",6, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // functDecls ::= functDecls COMMA functDecl 
            {
              LinkedList<ArgumentInfo> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).right;
		LinkedList<ArgumentInfo> l = (LinkedList<ArgumentInfo>)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		ArgumentInfo f = (ArgumentInfo)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		
		l.add(f);
		RESULT = l;
	
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("functDecls",6, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // funct ::= FUNCTION IDENTIFIER LPAR functDecls RPAR COLON type block 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-6)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-6)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-6)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-4)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-4)).right;
		LinkedList<ArgumentInfo> f = (LinkedList<ArgumentInfo>)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-4)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		SyntaxTree b = (SyntaxTree)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		
			FunctionInfo fctInfo = new FunctionInfo(f, t, b);
			Main.fctTable.put(id, fctInfo);
			
			System.out.println("\n\nFCT : " + Main.fctTable.toString() + "\n");
		
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("funct",2, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-7)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // BOOLEXP ::= FALSEEXP 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		RESULT = t; 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("BOOLEXP",12, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // BOOLEXP ::= TRUEEXP 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$LeaParser$stack.peek()).value;
		RESULT = t; 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("BOOLEXP",12, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // decl ::= IDENTIFIER COLON type AFF expr SEMIC 
            {
              Instruction RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-5)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-5)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).right;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).value;
		
		if(Main.currentNode != null)
		{
			Main.currentNode.getEnvironment().put(id, new VariableInfo(t, true));
			
			System.out.println("ENV : " + Main.currentNode.getEnvironment().toString());
			RESULT = new Assignment(new VariableLeaf(id, t), e); 
		}
		else
			System.out.println("DイLARATION VARIABLE GLOBALE INTERDITE!! FAUT GコER CA ICI!");
	
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("decl",4, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-5)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // decl ::= IDENTIFIER COLON type SEMIC 
            {
              Instruction RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).right;
		Type t = (Type)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).value;
		
		if(Main.currentNode != null)
		{
			Main.currentNode.getEnvironment().put(id, new VariableInfo(t, false));
			System.out.println("ENV : " + Main.currentNode.getEnvironment().toString());
		}
		else
			System.out.println("DイLARATION VARIABLE GLOBALE INTERDITE!! FAUT GコER CA ICI!");
			
		RESULT = new Assignment(new VariableLeaf(id, t), null);
	
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("decl",4, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // block ::= LBRACE NT$0 instrs RBRACE 
            {
              SyntaxTree RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (SyntaxTree) ((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-2)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).right;
		Instruction i = (Instruction)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).value;
		 RESULT = i; 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("block",8, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // NT$0 ::= 
            {
              SyntaxTree RESULT =null;

	    System.out.println("BLOCK");
	    SyntaxTree sTree = new SyntaxTree(null, null);
	    
	    Main.currentNode = sTree;
	
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("NT$0",14, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // constDecl ::= IDENTIFIER EQ INTEGER SEMIC 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).value;
		
		  	Main.constTable.put(id, new IntConstant(i));
		  	System.out.println("\nCONST : " + Main.constTable.toString() + "\n");
		
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("constDecl",1, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-3)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // type ::= BOOL 
            {
              Type RESULT =null;
		 RESULT = new BoolType(); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // type ::= STRING 
            {
              Type RESULT =null;
		 RESULT = new StringType(); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // type ::= CHAR 
            {
              Type RESULT =null;
		 RESULT = new CharType(); 
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // type ::= FLOAT 
            {
              Type RESULT =null;
		 RESULT = new FloatType();  
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // type ::= INT 
            {
              Type RESULT =null;
		 RESULT = new IntType();  
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("type",5, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // axiom ::= constDecl 
            {
              Object RESULT =null;

              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("axiom",0, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // axiom ::= funct axiom 
            {
              Object RESULT =null;

              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("axiom",0, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // axiom ::= constDecl axiom 
            {
              Object RESULT =null;

              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("axiom",0, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // axiom ::= funct 
            {
              Object RESULT =null;

              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("axiom",0, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          return CUP$LeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= axiom EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)).value;
		RESULT = start_val;
              CUP$LeaParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$LeaParser$stack.elementAt(CUP$LeaParser$top-1)), ((java_cup.runtime.Symbol)CUP$LeaParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$LeaParser$parser.done_parsing();
          return CUP$LeaParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

