
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 25 15:41:01 CET 2012
//----------------------------------------------------

package lea;

/** CUP generated class containing symbol constants. */
public class LeaSymbol {
  /* terminals */
  public static final int STRINGEXP = 48;
  public static final int LBRACKET = 12;
  public static final int MULT = 28;
  public static final int CHAR = 33;
  public static final int GE = 22;
  public static final int CASE = 44;
  public static final int SEMIC = 14;
  public static final int INTEGER = 46;
  public static final int REPEAT = 42;
  public static final int INT = 30;
  public static final int MINUS = 26;
  public static final int AND = 17;
  public static final int LT = 19;
  public static final int RPAR = 9;
  public static final int OR = 18;
  public static final int BOOL = 43;
  public static final int COMMA = 34;
  public static final int DIV = 29;
  public static final int PLUS = 25;
  public static final int IF = 2;
  public static final int LE = 21;
  public static final int FLOATING = 47;
  public static final int OF = 7;
  public static final int EOF = 0;
  public static final int RBRACKET = 13;
  public static final int TRUE = 36;
  public static final int error = 1;
  public static final int MODULO = 40;
  public static final int SLOT = 38;
  public static final int EQ = 23;
  public static final int COLON = 15;
  public static final int LBRACE = 10;
  public static final int ELSE = 4;
  public static final int TO = 41;
  public static final int WHILE = 5;
  public static final int LIST = 39;
  public static final int FLOAT = 31;
  public static final int THEN = 3;
  public static final int RBRACE = 11;
  public static final int LPAR = 8;
  public static final int STRING = 32;
  public static final int DIFF = 24;
  public static final int MINUS_U = 27;
  public static final int AFF = 16;
  public static final int FALSE = 37;
  public static final int STRUCT = 35;
  public static final int GT = 20;
  public static final int DO = 6;
  public static final int IDENTIFIER = 45;
}

