
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Dec 01 16:14:23 CET 2012
//----------------------------------------------------

package lea;

/** CUP generated class containing symbol constants. */
public class LeaSymbol {
  /* terminals */
  public static final int TRUEEXP = 43;
  public static final int FUNCTION = 3;
  public static final int STRINGEXP = 41;
  public static final int MULT = 35;
  public static final int CHAR = 12;
  public static final int GE = 29;
  public static final int CASE = 17;
  public static final int SEMIC = 2;
  public static final int INTEGER = 39;
  public static final int REPEAT = 19;
  public static final int INT = 9;
  public static final int MINUS = 33;
  public static final int AND = 24;
  public static final int LT = 26;
  public static final int RPAR = 5;
  public static final int OR = 25;
  public static final int BOOL = 13;
  public static final int COMMA = 14;
  public static final int DIV = 36;
  public static final int PLUS = 32;
  public static final int IF = 15;
  public static final int LE = 28;
  public static final int EOF = 0;
  public static final int RETURN = 23;
  public static final int error = 1;
  public static final int MODULO = 37;
  public static final int FLOATEXP = 40;
  public static final int SLOT = 21;
  public static final int EQ = 30;
  public static final int CHAREXP = 42;
  public static final int COLON = 6;
  public static final int LBRACE = 7;
  public static final int ELSE = 16;
  public static final int TO = 22;
  public static final int WHILE = 18;
  public static final int FLOAT = 10;
  public static final int RBRACE = 8;
  public static final int LPAR = 4;
  public static final int STRING = 11;
  public static final int DIFF = 31;
  public static final int MINUS_U = 34;
  public static final int AFF = 20;
  public static final int FALSEEXP = 44;
  public static final int GT = 27;
  public static final int IDENTIFIER = 38;
}

