
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 29 12:52:33 CET 2012
//----------------------------------------------------

package lea;

/** CUP generated class containing symbol constants. */
public class LeaSymbol {
  /* terminals */
  public static final int INTEGER = 5;
  public static final int LBRACE = 6;
  public static final int EQ = 2;
  public static final int error = 1;
  public static final int IDENTIFIER = 4;
  public static final int SEMIC = 3;
  public static final int EOF = 0;
}

