
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 21 16:05:22 CET 2012
//----------------------------------------------------

package org.tp;

/** CUP generated class containing symbol constants. */
public class LeaSymbol {
  /* terminals */
  public static final int STRINGEXP = 51;
  public static final int LBRACKET = 15;
  public static final int MULT = 31;
  public static final int CHAR = 36;
  public static final int GE = 25;
  public static final int CASE = 47;
  public static final int SEMIC = 17;
  public static final int INTEGER = 49;
  public static final int REPEAT = 45;
  public static final int INT = 33;
  public static final int ARRAY = 8;
  public static final int MINUS = 29;
  public static final int AND = 20;
  public static final int LT = 22;
  public static final int RPAR = 12;
  public static final int OR = 21;
  public static final int BOOL = 46;
  public static final int COMMA = 37;
  public static final int DIV = 32;
  public static final int PLUS = 28;
  public static final int IF = 2;
  public static final int LE = 24;
  public static final int FLOATING = 50;
  public static final int OF = 10;
  public static final int EOF = 0;
  public static final int RBRACKET = 16;
  public static final int TRUE = 39;
  public static final int error = 1;
  public static final int MODULO = 43;
  public static final int SLOT = 41;
  public static final int EQ = 26;
  public static final int COLON = 18;
  public static final int LBRACE = 13;
  public static final int ELSE = 4;
  public static final int TO = 44;
  public static final int WHILE = 5;
  public static final int LIST = 42;
  public static final int FLOAT = 34;
  public static final int THEN = 3;
  public static final int RBRACE = 14;
  public static final int STRING = 35;
  public static final int LPAR = 11;
  public static final int DIFF = 27;
  public static final int MINUS_U = 30;
  public static final int AFF = 19;
  public static final int FALSE = 40;
  public static final int POINTER = 9;
  public static final int STRUCT = 38;
  public static final int GT = 23;
  public static final int VAR = 7;
  public static final int DO = 6;
  public static final int IDENTIFIER = 48;
}

